// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: grSim_Commands.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from grSim_Commands.proto</summary>
public static partial class GrSimCommandsReflection {

  #region Descriptor
  /// <summary>File descriptor for grSim_Commands.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GrSimCommandsReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChRnclNpbV9Db21tYW5kcy5wcm90bxoNenNzX2NtZC5wcm90byJqCg5nclNp",
          "bV9Db21tYW5kcxIRCgl0aW1lc3RhbXAYASABKAESFAoMaXN0ZWFteWVsbG93",
          "GAIgASgIEi8KDnJvYm90X2NvbW1hbmRzGAMgASgLMhcuWlNTLk5ldy5Sb2Jv",
          "dHNfQ29tbWFuZGIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ZSS.New.ZssCmdReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::grSim_Commands), global::grSim_Commands.Parser, new[]{ "Timestamp", "Isteamyellow", "RobotCommands" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class grSim_Commands : pb::IMessage<grSim_Commands>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<grSim_Commands> _parser = new pb::MessageParser<grSim_Commands>(() => new grSim_Commands());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<grSim_Commands> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GrSimCommandsReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public grSim_Commands() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public grSim_Commands(grSim_Commands other) : this() {
    timestamp_ = other.timestamp_;
    isteamyellow_ = other.isteamyellow_;
    robotCommands_ = other.robotCommands_ != null ? other.robotCommands_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public grSim_Commands Clone() {
    return new grSim_Commands(this);
  }

  /// <summary>Field number for the "timestamp" field.</summary>
  public const int TimestampFieldNumber = 1;
  private double timestamp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Timestamp {
    get { return timestamp_; }
    set {
      timestamp_ = value;
    }
  }

  /// <summary>Field number for the "isteamyellow" field.</summary>
  public const int IsteamyellowFieldNumber = 2;
  private bool isteamyellow_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Isteamyellow {
    get { return isteamyellow_; }
    set {
      isteamyellow_ = value;
    }
  }

  /// <summary>Field number for the "robot_commands" field.</summary>
  public const int RobotCommandsFieldNumber = 3;
  private global::ZSS.New.Robots_Command robotCommands_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ZSS.New.Robots_Command RobotCommands {
    get { return robotCommands_; }
    set {
      robotCommands_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as grSim_Commands);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(grSim_Commands other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Timestamp, other.Timestamp)) return false;
    if (Isteamyellow != other.Isteamyellow) return false;
    if (!object.Equals(RobotCommands, other.RobotCommands)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Timestamp != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Timestamp);
    if (Isteamyellow != false) hash ^= Isteamyellow.GetHashCode();
    if (robotCommands_ != null) hash ^= RobotCommands.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Timestamp != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(Timestamp);
    }
    if (Isteamyellow != false) {
      output.WriteRawTag(16);
      output.WriteBool(Isteamyellow);
    }
    if (robotCommands_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(RobotCommands);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Timestamp != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(Timestamp);
    }
    if (Isteamyellow != false) {
      output.WriteRawTag(16);
      output.WriteBool(Isteamyellow);
    }
    if (robotCommands_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(RobotCommands);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Timestamp != 0D) {
      size += 1 + 8;
    }
    if (Isteamyellow != false) {
      size += 1 + 1;
    }
    if (robotCommands_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(RobotCommands);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(grSim_Commands other) {
    if (other == null) {
      return;
    }
    if (other.Timestamp != 0D) {
      Timestamp = other.Timestamp;
    }
    if (other.Isteamyellow != false) {
      Isteamyellow = other.Isteamyellow;
    }
    if (other.robotCommands_ != null) {
      if (robotCommands_ == null) {
        RobotCommands = new global::ZSS.New.Robots_Command();
      }
      RobotCommands.MergeFrom(other.RobotCommands);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 9: {
          Timestamp = input.ReadDouble();
          break;
        }
        case 16: {
          Isteamyellow = input.ReadBool();
          break;
        }
        case 26: {
          if (robotCommands_ == null) {
            RobotCommands = new global::ZSS.New.Robots_Command();
          }
          input.ReadMessage(RobotCommands);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 9: {
          Timestamp = input.ReadDouble();
          break;
        }
        case 16: {
          Isteamyellow = input.ReadBool();
          break;
        }
        case 26: {
          if (robotCommands_ == null) {
            RobotCommands = new global::ZSS.New.Robots_Command();
          }
          input.ReadMessage(RobotCommands);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
