// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ssl_game_controller_auto_ref.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ssl_game_controller_auto_ref.proto</summary>
public static partial class SslGameControllerAutoRefReflection {

  #region Descriptor
  /// <summary>File descriptor for ssl_game_controller_auto_ref.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static SslGameControllerAutoRefReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CiJzc2xfZ2FtZV9jb250cm9sbGVyX2F1dG9fcmVmLnByb3RvGiBzc2xfZ2Ft",
          "ZV9jb250cm9sbGVyX2NvbW1vbi5wcm90bxoZc3NsX2dhbWVfZXZlbnRfMjAx",
          "OS5wcm90byJIChNBdXRvUmVmUmVnaXN0cmF0aW9uEhIKCmlkZW50aWZpZXIY",
          "ASACKAkSHQoJc2lnbmF0dXJlGAIgASgLMgouU2lnbmF0dXJlIoMBChNBdXRv",
          "UmVmVG9Db250cm9sbGVyEh0KCXNpZ25hdHVyZRgBIAEoCzIKLlNpZ25hdHVy",
          "ZRIeCgpnYW1lX2V2ZW50GAIgASgLMgouR2FtZUV2ZW50Ei0KEGF1dG9fcmVm",
          "X21lc3NhZ2UYAyABKAsyDy5BdXRvUmVmTWVzc2FnZUICGAEiSgoTQ29udHJv",
          "bGxlclRvQXV0b1JlZhIsChBjb250cm9sbGVyX3JlcGx5GAEgASgLMhAuQ29u",
          "dHJvbGxlclJlcGx5SABCBQoDbXNnIuEBCg5BdXRvUmVmTWVzc2FnZRIQCgZj",
          "dXN0b20YASABKAlIABI0Cg13YWl0X2Zvcl9ib3RzGAIgASgLMhsuQXV0b1Jl",
          "Zk1lc3NhZ2UuV2FpdEZvckJvdHNIABp8CgtXYWl0Rm9yQm90cxI3Cgl2aW9s",
          "YXRvcnMYASADKAsyJC5BdXRvUmVmTWVzc2FnZS5XYWl0Rm9yQm90cy5WaW9s",
          "YXRvcho0CghWaW9sYXRvchIWCgZib3RfaWQYASACKAsyBi5Cb3RJZBIQCghk",
          "aXN0YW5jZRgCIAIoAkIJCgdtZXNzYWdl"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::SslGameControllerCommonReflection.Descriptor, global::SslGameEvent2019Reflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::AutoRefRegistration), global::AutoRefRegistration.Parser, new[]{ "Identifier", "Signature" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::AutoRefToController), global::AutoRefToController.Parser, new[]{ "Signature", "GameEvent", "AutoRefMessage" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ControllerToAutoRef), global::ControllerToAutoRef.Parser, new[]{ "ControllerReply" }, new[]{ "Msg" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::AutoRefMessage), global::AutoRefMessage.Parser, new[]{ "Custom", "WaitForBots" }, new[]{ "Message" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::AutoRefMessage.Types.WaitForBots), global::AutoRefMessage.Types.WaitForBots.Parser, new[]{ "Violators" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::AutoRefMessage.Types.WaitForBots.Types.Violator), global::AutoRefMessage.Types.WaitForBots.Types.Violator.Parser, new[]{ "BotId", "Distance" }, null, null, null, null)})})
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// AutoRefRegistration is the first message that a client must send to the controller to identify itself
/// </summary>
public sealed partial class AutoRefRegistration : pb::IMessage<AutoRefRegistration>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<AutoRefRegistration> _parser = new pb::MessageParser<AutoRefRegistration>(() => new AutoRefRegistration());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<AutoRefRegistration> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SslGameControllerAutoRefReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AutoRefRegistration() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AutoRefRegistration(AutoRefRegistration other) : this() {
    identifier_ = other.identifier_;
    signature_ = other.signature_ != null ? other.signature_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AutoRefRegistration Clone() {
    return new AutoRefRegistration(this);
  }

  /// <summary>Field number for the "identifier" field.</summary>
  public const int IdentifierFieldNumber = 1;
  private readonly static string IdentifierDefaultValue = "";

  private string identifier_;
  /// <summary>
  /// identifier is a unique name of the client
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Identifier {
    get { return identifier_ ?? IdentifierDefaultValue; }
    set {
      identifier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "identifier" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasIdentifier {
    get { return identifier_ != null; }
  }
  /// <summary>Clears the value of the "identifier" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearIdentifier() {
    identifier_ = null;
  }

  /// <summary>Field number for the "signature" field.</summary>
  public const int SignatureFieldNumber = 2;
  private global::Signature signature_;
  /// <summary>
  /// signature can optionally be specified to enable secure communication
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Signature Signature {
    get { return signature_; }
    set {
      signature_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as AutoRefRegistration);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(AutoRefRegistration other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Identifier != other.Identifier) return false;
    if (!object.Equals(Signature, other.Signature)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasIdentifier) hash ^= Identifier.GetHashCode();
    if (signature_ != null) hash ^= Signature.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasIdentifier) {
      output.WriteRawTag(10);
      output.WriteString(Identifier);
    }
    if (signature_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Signature);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasIdentifier) {
      output.WriteRawTag(10);
      output.WriteString(Identifier);
    }
    if (signature_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Signature);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasIdentifier) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Identifier);
    }
    if (signature_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Signature);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(AutoRefRegistration other) {
    if (other == null) {
      return;
    }
    if (other.HasIdentifier) {
      Identifier = other.Identifier;
    }
    if (other.signature_ != null) {
      if (signature_ == null) {
        Signature = new global::Signature();
      }
      Signature.MergeFrom(other.Signature);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Identifier = input.ReadString();
          break;
        }
        case 18: {
          if (signature_ == null) {
            Signature = new global::Signature();
          }
          input.ReadMessage(Signature);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Identifier = input.ReadString();
          break;
        }
        case 18: {
          if (signature_ == null) {
            Signature = new global::Signature();
          }
          input.ReadMessage(Signature);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// AutoRefToController is the wrapper message for all subsequent messages from the autoRef to the controller
/// </summary>
public sealed partial class AutoRefToController : pb::IMessage<AutoRefToController>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<AutoRefToController> _parser = new pb::MessageParser<AutoRefToController>(() => new AutoRefToController());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<AutoRefToController> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SslGameControllerAutoRefReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AutoRefToController() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AutoRefToController(AutoRefToController other) : this() {
    signature_ = other.signature_ != null ? other.signature_.Clone() : null;
    gameEvent_ = other.gameEvent_ != null ? other.gameEvent_.Clone() : null;
    autoRefMessage_ = other.autoRefMessage_ != null ? other.autoRefMessage_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AutoRefToController Clone() {
    return new AutoRefToController(this);
  }

  /// <summary>Field number for the "signature" field.</summary>
  public const int SignatureFieldNumber = 1;
  private global::Signature signature_;
  /// <summary>
  /// signature can optionally be specified to enable secure communication
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Signature Signature {
    get { return signature_; }
    set {
      signature_ = value;
    }
  }

  /// <summary>Field number for the "game_event" field.</summary>
  public const int GameEventFieldNumber = 2;
  private global::GameEvent gameEvent_;
  /// <summary>
  /// game_event is an optional event that the autoRef detected during the game
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::GameEvent GameEvent {
    get { return gameEvent_; }
    set {
      gameEvent_ = value;
    }
  }

  /// <summary>Field number for the "auto_ref_message" field.</summary>
  public const int AutoRefMessageFieldNumber = 3;
  private global::AutoRefMessage autoRefMessage_;
  /// <summary>
  /// auto_ref_message is an optional message that describes the current state or situation of the game/autoRef
  /// it is not and never was processed by the GC and is this marked deprecated
  /// </summary>
  [global::System.ObsoleteAttribute]
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::AutoRefMessage AutoRefMessage {
    get { return autoRefMessage_; }
    set {
      autoRefMessage_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as AutoRefToController);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(AutoRefToController other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Signature, other.Signature)) return false;
    if (!object.Equals(GameEvent, other.GameEvent)) return false;
    if (!object.Equals(AutoRefMessage, other.AutoRefMessage)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (signature_ != null) hash ^= Signature.GetHashCode();
    if (gameEvent_ != null) hash ^= GameEvent.GetHashCode();
    if (autoRefMessage_ != null) hash ^= AutoRefMessage.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (signature_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Signature);
    }
    if (gameEvent_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(GameEvent);
    }
    if (autoRefMessage_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(AutoRefMessage);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (signature_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Signature);
    }
    if (gameEvent_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(GameEvent);
    }
    if (autoRefMessage_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(AutoRefMessage);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (signature_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Signature);
    }
    if (gameEvent_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(GameEvent);
    }
    if (autoRefMessage_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(AutoRefMessage);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(AutoRefToController other) {
    if (other == null) {
      return;
    }
    if (other.signature_ != null) {
      if (signature_ == null) {
        Signature = new global::Signature();
      }
      Signature.MergeFrom(other.Signature);
    }
    if (other.gameEvent_ != null) {
      if (gameEvent_ == null) {
        GameEvent = new global::GameEvent();
      }
      GameEvent.MergeFrom(other.GameEvent);
    }
    if (other.autoRefMessage_ != null) {
      if (autoRefMessage_ == null) {
        AutoRefMessage = new global::AutoRefMessage();
      }
      AutoRefMessage.MergeFrom(other.AutoRefMessage);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (signature_ == null) {
            Signature = new global::Signature();
          }
          input.ReadMessage(Signature);
          break;
        }
        case 18: {
          if (gameEvent_ == null) {
            GameEvent = new global::GameEvent();
          }
          input.ReadMessage(GameEvent);
          break;
        }
        case 26: {
          if (autoRefMessage_ == null) {
            AutoRefMessage = new global::AutoRefMessage();
          }
          input.ReadMessage(AutoRefMessage);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (signature_ == null) {
            Signature = new global::Signature();
          }
          input.ReadMessage(Signature);
          break;
        }
        case 18: {
          if (gameEvent_ == null) {
            GameEvent = new global::GameEvent();
          }
          input.ReadMessage(GameEvent);
          break;
        }
        case 26: {
          if (autoRefMessage_ == null) {
            AutoRefMessage = new global::AutoRefMessage();
          }
          input.ReadMessage(AutoRefMessage);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// ControllerToAutoRef is the wrapper message for all messages from controller to autoRef
/// </summary>
public sealed partial class ControllerToAutoRef : pb::IMessage<ControllerToAutoRef>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ControllerToAutoRef> _parser = new pb::MessageParser<ControllerToAutoRef>(() => new ControllerToAutoRef());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ControllerToAutoRef> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SslGameControllerAutoRefReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ControllerToAutoRef() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ControllerToAutoRef(ControllerToAutoRef other) : this() {
    switch (other.MsgCase) {
      case MsgOneofCase.ControllerReply:
        ControllerReply = other.ControllerReply.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ControllerToAutoRef Clone() {
    return new ControllerToAutoRef(this);
  }

  /// <summary>Field number for the "controller_reply" field.</summary>
  public const int ControllerReplyFieldNumber = 1;
  /// <summary>
  /// a reply from the controller
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ControllerReply ControllerReply {
    get { return msgCase_ == MsgOneofCase.ControllerReply ? (global::ControllerReply) msg_ : null; }
    set {
      msg_ = value;
      msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.ControllerReply;
    }
  }

  private object msg_;
  /// <summary>Enum of possible cases for the "msg" oneof.</summary>
  public enum MsgOneofCase {
    None = 0,
    ControllerReply = 1,
  }
  private MsgOneofCase msgCase_ = MsgOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MsgOneofCase MsgCase {
    get { return msgCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearMsg() {
    msgCase_ = MsgOneofCase.None;
    msg_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ControllerToAutoRef);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ControllerToAutoRef other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(ControllerReply, other.ControllerReply)) return false;
    if (MsgCase != other.MsgCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (msgCase_ == MsgOneofCase.ControllerReply) hash ^= ControllerReply.GetHashCode();
    hash ^= (int) msgCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (msgCase_ == MsgOneofCase.ControllerReply) {
      output.WriteRawTag(10);
      output.WriteMessage(ControllerReply);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (msgCase_ == MsgOneofCase.ControllerReply) {
      output.WriteRawTag(10);
      output.WriteMessage(ControllerReply);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (msgCase_ == MsgOneofCase.ControllerReply) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ControllerReply);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ControllerToAutoRef other) {
    if (other == null) {
      return;
    }
    switch (other.MsgCase) {
      case MsgOneofCase.ControllerReply:
        if (ControllerReply == null) {
          ControllerReply = new global::ControllerReply();
        }
        ControllerReply.MergeFrom(other.ControllerReply);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          global::ControllerReply subBuilder = new global::ControllerReply();
          if (msgCase_ == MsgOneofCase.ControllerReply) {
            subBuilder.MergeFrom(ControllerReply);
          }
          input.ReadMessage(subBuilder);
          ControllerReply = subBuilder;
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          global::ControllerReply subBuilder = new global::ControllerReply();
          if (msgCase_ == MsgOneofCase.ControllerReply) {
            subBuilder.MergeFrom(ControllerReply);
          }
          input.ReadMessage(subBuilder);
          ControllerReply = subBuilder;
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// a message from autoRef, describing the current state or situation
/// </summary>
public sealed partial class AutoRefMessage : pb::IMessage<AutoRefMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<AutoRefMessage> _parser = new pb::MessageParser<AutoRefMessage>(() => new AutoRefMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<AutoRefMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SslGameControllerAutoRefReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AutoRefMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AutoRefMessage(AutoRefMessage other) : this() {
    switch (other.MessageCase) {
      case MessageOneofCase.Custom:
        Custom = other.Custom;
        break;
      case MessageOneofCase.WaitForBots:
        WaitForBots = other.WaitForBots.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AutoRefMessage Clone() {
    return new AutoRefMessage(this);
  }

  /// <summary>Field number for the "custom" field.</summary>
  public const int CustomFieldNumber = 1;
  /// <summary>
  /// a custom message
  /// an empty string indicates that there is no message
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Custom {
    get { return HasCustom ? (string) message_ : ""; }
    set {
      message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      messageCase_ = MessageOneofCase.Custom;
    }
  }
  /// <summary>Gets whether the "custom" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasCustom {
    get { return messageCase_ == MessageOneofCase.Custom; }
  }
  /// <summary> Clears the value of the oneof if it's currently set to "custom" </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearCustom() {
    if (HasCustom) {
      ClearMessage();
    }
  }

  /// <summary>Field number for the "wait_for_bots" field.</summary>
  public const int WaitForBotsFieldNumber = 2;
  /// <summary>
  /// one or more bots are at invalid locations and need to move
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::AutoRefMessage.Types.WaitForBots WaitForBots {
    get { return messageCase_ == MessageOneofCase.WaitForBots ? (global::AutoRefMessage.Types.WaitForBots) message_ : null; }
    set {
      message_ = value;
      messageCase_ = value == null ? MessageOneofCase.None : MessageOneofCase.WaitForBots;
    }
  }

  private object message_;
  /// <summary>Enum of possible cases for the "message" oneof.</summary>
  public enum MessageOneofCase {
    None = 0,
    Custom = 1,
    WaitForBots = 2,
  }
  private MessageOneofCase messageCase_ = MessageOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MessageOneofCase MessageCase {
    get { return messageCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearMessage() {
    messageCase_ = MessageOneofCase.None;
    message_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as AutoRefMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(AutoRefMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Custom != other.Custom) return false;
    if (!object.Equals(WaitForBots, other.WaitForBots)) return false;
    if (MessageCase != other.MessageCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasCustom) hash ^= Custom.GetHashCode();
    if (messageCase_ == MessageOneofCase.WaitForBots) hash ^= WaitForBots.GetHashCode();
    hash ^= (int) messageCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasCustom) {
      output.WriteRawTag(10);
      output.WriteString(Custom);
    }
    if (messageCase_ == MessageOneofCase.WaitForBots) {
      output.WriteRawTag(18);
      output.WriteMessage(WaitForBots);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasCustom) {
      output.WriteRawTag(10);
      output.WriteString(Custom);
    }
    if (messageCase_ == MessageOneofCase.WaitForBots) {
      output.WriteRawTag(18);
      output.WriteMessage(WaitForBots);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasCustom) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Custom);
    }
    if (messageCase_ == MessageOneofCase.WaitForBots) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(WaitForBots);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(AutoRefMessage other) {
    if (other == null) {
      return;
    }
    switch (other.MessageCase) {
      case MessageOneofCase.Custom:
        Custom = other.Custom;
        break;
      case MessageOneofCase.WaitForBots:
        if (WaitForBots == null) {
          WaitForBots = new global::AutoRefMessage.Types.WaitForBots();
        }
        WaitForBots.MergeFrom(other.WaitForBots);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Custom = input.ReadString();
          break;
        }
        case 18: {
          global::AutoRefMessage.Types.WaitForBots subBuilder = new global::AutoRefMessage.Types.WaitForBots();
          if (messageCase_ == MessageOneofCase.WaitForBots) {
            subBuilder.MergeFrom(WaitForBots);
          }
          input.ReadMessage(subBuilder);
          WaitForBots = subBuilder;
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Custom = input.ReadString();
          break;
        }
        case 18: {
          global::AutoRefMessage.Types.WaitForBots subBuilder = new global::AutoRefMessage.Types.WaitForBots();
          if (messageCase_ == MessageOneofCase.WaitForBots) {
            subBuilder.MergeFrom(WaitForBots);
          }
          input.ReadMessage(subBuilder);
          WaitForBots = subBuilder;
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the AutoRefMessage message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    /// <summary>
    /// the bots that is waited for
    /// </summary>
    public sealed partial class WaitForBots : pb::IMessage<WaitForBots>
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
    #endif
    {
      private static readonly pb::MessageParser<WaitForBots> _parser = new pb::MessageParser<WaitForBots>(() => new WaitForBots());
      private pb::UnknownFieldSet _unknownFields;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pb::MessageParser<WaitForBots> Parser { get { return _parser; } }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pbr::MessageDescriptor Descriptor {
        get { return global::AutoRefMessage.Descriptor.NestedTypes[0]; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public WaitForBots() {
        OnConstruction();
      }

      partial void OnConstruction();

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public WaitForBots(WaitForBots other) : this() {
        violators_ = other.violators_.Clone();
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public WaitForBots Clone() {
        return new WaitForBots(this);
      }

      /// <summary>Field number for the "violators" field.</summary>
      public const int ViolatorsFieldNumber = 1;
      private static readonly pb::FieldCodec<global::AutoRefMessage.Types.WaitForBots.Types.Violator> _repeated_violators_codec
          = pb::FieldCodec.ForMessage(10, global::AutoRefMessage.Types.WaitForBots.Types.Violator.Parser);
      private readonly pbc::RepeatedField<global::AutoRefMessage.Types.WaitForBots.Types.Violator> violators_ = new pbc::RepeatedField<global::AutoRefMessage.Types.WaitForBots.Types.Violator>();
      /// <summary>
      /// the bots that are waited for
      /// </summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public pbc::RepeatedField<global::AutoRefMessage.Types.WaitForBots.Types.Violator> Violators {
        get { return violators_; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override bool Equals(object other) {
        return Equals(other as WaitForBots);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool Equals(WaitForBots other) {
        if (ReferenceEquals(other, null)) {
          return false;
        }
        if (ReferenceEquals(other, this)) {
          return true;
        }
        if(!violators_.Equals(other.violators_)) return false;
        return Equals(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override int GetHashCode() {
        int hash = 1;
        hash ^= violators_.GetHashCode();
        if (_unknownFields != null) {
          hash ^= _unknownFields.GetHashCode();
        }
        return hash;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void WriteTo(pb::CodedOutputStream output) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
      #else
        violators_.WriteTo(output, _repeated_violators_codec);
        if (_unknownFields != null) {
          _unknownFields.WriteTo(output);
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
        violators_.WriteTo(ref output, _repeated_violators_codec);
        if (_unknownFields != null) {
          _unknownFields.WriteTo(ref output);
        }
      }
      #endif

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int CalculateSize() {
        int size = 0;
        size += violators_.CalculateSize(_repeated_violators_codec);
        if (_unknownFields != null) {
          size += _unknownFields.CalculateSize();
        }
        return size;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(WaitForBots other) {
        if (other == null) {
          return;
        }
        violators_.Add(other.violators_);
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(pb::CodedInputStream input) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
      #else
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
          switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
              break;
            case 10: {
              violators_.AddEntriesFrom(input, _repeated_violators_codec);
              break;
            }
          }
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
          switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
              break;
            case 10: {
              violators_.AddEntriesFrom(ref input, _repeated_violators_codec);
              break;
            }
          }
        }
      }
      #endif

      #region Nested types
      /// <summary>Container for nested types declared in the WaitForBots message type.</summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static partial class Types {
        public sealed partial class Violator : pb::IMessage<Violator>
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            , pb::IBufferMessage
        #endif
        {
          private static readonly pb::MessageParser<Violator> _parser = new pb::MessageParser<Violator>(() => new Violator());
          private pb::UnknownFieldSet _unknownFields;
          private int _hasBits0;
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public static pb::MessageParser<Violator> Parser { get { return _parser; } }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public static pbr::MessageDescriptor Descriptor {
            get { return global::AutoRefMessage.Types.WaitForBots.Descriptor.NestedTypes[0]; }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          pbr::MessageDescriptor pb::IMessage.Descriptor {
            get { return Descriptor; }
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public Violator() {
            OnConstruction();
          }

          partial void OnConstruction();

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public Violator(Violator other) : this() {
            _hasBits0 = other._hasBits0;
            botId_ = other.botId_ != null ? other.botId_.Clone() : null;
            distance_ = other.distance_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public Violator Clone() {
            return new Violator(this);
          }

          /// <summary>Field number for the "bot_id" field.</summary>
          public const int BotIdFieldNumber = 1;
          private global::BotId botId_;
          /// <summary>
          /// the id of the violator
          /// </summary>
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public global::BotId BotId {
            get { return botId_; }
            set {
              botId_ = value;
            }
          }

          /// <summary>Field number for the "distance" field.</summary>
          public const int DistanceFieldNumber = 2;
          private readonly static float DistanceDefaultValue = 0F;

          private float distance_;
          /// <summary>
          /// the distance to the next valid position
          /// </summary>
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public float Distance {
            get { if ((_hasBits0 & 1) != 0) { return distance_; } else { return DistanceDefaultValue; } }
            set {
              _hasBits0 |= 1;
              distance_ = value;
            }
          }
          /// <summary>Gets whether the "distance" field is set</summary>
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public bool HasDistance {
            get { return (_hasBits0 & 1) != 0; }
          }
          /// <summary>Clears the value of the "distance" field</summary>
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void ClearDistance() {
            _hasBits0 &= ~1;
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public override bool Equals(object other) {
            return Equals(other as Violator);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public bool Equals(Violator other) {
            if (ReferenceEquals(other, null)) {
              return false;
            }
            if (ReferenceEquals(other, this)) {
              return true;
            }
            if (!object.Equals(BotId, other.BotId)) return false;
            if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Distance, other.Distance)) return false;
            return Equals(_unknownFields, other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public override int GetHashCode() {
            int hash = 1;
            if (botId_ != null) hash ^= BotId.GetHashCode();
            if (HasDistance) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Distance);
            if (_unknownFields != null) {
              hash ^= _unknownFields.GetHashCode();
            }
            return hash;
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public override string ToString() {
            return pb::JsonFormatter.ToDiagnosticString(this);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void WriteTo(pb::CodedOutputStream output) {
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
          #else
            if (botId_ != null) {
              output.WriteRawTag(10);
              output.WriteMessage(BotId);
            }
            if (HasDistance) {
              output.WriteRawTag(21);
              output.WriteFloat(Distance);
            }
            if (_unknownFields != null) {
              _unknownFields.WriteTo(output);
            }
          #endif
          }

          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
            if (botId_ != null) {
              output.WriteRawTag(10);
              output.WriteMessage(BotId);
            }
            if (HasDistance) {
              output.WriteRawTag(21);
              output.WriteFloat(Distance);
            }
            if (_unknownFields != null) {
              _unknownFields.WriteTo(ref output);
            }
          }
          #endif

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public int CalculateSize() {
            int size = 0;
            if (botId_ != null) {
              size += 1 + pb::CodedOutputStream.ComputeMessageSize(BotId);
            }
            if (HasDistance) {
              size += 1 + 4;
            }
            if (_unknownFields != null) {
              size += _unknownFields.CalculateSize();
            }
            return size;
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void MergeFrom(Violator other) {
            if (other == null) {
              return;
            }
            if (other.botId_ != null) {
              if (botId_ == null) {
                BotId = new global::BotId();
              }
              BotId.MergeFrom(other.BotId);
            }
            if (other.HasDistance) {
              Distance = other.Distance;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
          }

          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          public void MergeFrom(pb::CodedInputStream input) {
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
          #else
            uint tag;
            while ((tag = input.ReadTag()) != 0) {
              switch(tag) {
                default:
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                  break;
                case 10: {
                  if (botId_ == null) {
                    BotId = new global::BotId();
                  }
                  input.ReadMessage(BotId);
                  break;
                }
                case 21: {
                  Distance = input.ReadFloat();
                  break;
                }
              }
            }
          #endif
          }

          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
          [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
          void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
            uint tag;
            while ((tag = input.ReadTag()) != 0) {
              switch(tag) {
                default:
                  _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                  break;
                case 10: {
                  if (botId_ == null) {
                    BotId = new global::BotId();
                  }
                  input.ReadMessage(BotId);
                  break;
                }
                case 21: {
                  Distance = input.ReadFloat();
                  break;
                }
              }
            }
          }
          #endif

        }

      }
      #endregion

    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
